PATH:
  PROCESSED_DB: '/mnt/pixel/ego4d_data/16822_data/0056_01/000'
  PROCESSED_QUERY: '/mnt/pixel/ego4d_data/16822_data/0056_01/000'

VDB_BUILDER:
  output: 'exhaustive'

EXTRACTOR:
  'output': 'superpoint'
  'model':
    'name': 'superpoint'
    'nms_radius': 3
    'max_keypoints': 4096
    'fix_sampling': True

MATCHER:
  'output': 'superglue'
  'model':
    'name': 'superglue'
    'weights': 'outdoor'
    'sinkhorn_iterations': 50

